language: node_js

node_js: stable

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add codecov greenkeeper-lockfile
  - git config --global user.name 'JounQin'
  - git config --global user.email 'admin@1stg.me'

before_script:
  - set -e
  - greenkeeper-lockfile-update

script:
  - yarn lint
  - yarn build
  - yarn test

after_script:
  - codecov
  - greenkeeper-lockfile-upload
